### ISSUE TITLE
Syntax error in sankey.py

### ISSUE THREAD

**Issue by dsvancer** [anazalea/pySankey#23]
Currently line 34 of sankey.py in the pySankey package is - if len(labels > 0): 
When the leftLabels or rightLabels arguments are provided to the sankey function, this generates an error.
Line 34 should be updated to if len(labels) > 0:

**Comment by Pierre-Sassoulas** [comment]
Fixed in pySankeyBeta, you can install it with :

`pip install pySankeyBeta`

**Comment by brianpenghe** [comment]
> Fixed in pySankeyBeta, you can install it with :
> 
> `pip install pySankeyBeta`

Can you put this command in README ?

**Comment by Pierre-Sassoulas** [comment]
@brianpenghe No, if I could merge, I would merge the correction directly ;)

**Comment by kenosborne** [comment]
Well, if the pySankeyBeta is based on the github webpage 
https://github.com/anazalea/pySankey/blob/master/pysankey/sankey.py
then the error is still there (on line 42).

I haven't tried the pysankey beta, but am going to try to modify my local copy of the library to see if I can't get the functionality I'm looking for.

**Comment by Pierre-Sassoulas** [comment]
@kenosborne, PySankeyBeta is based on https://github.com/Pierre-Sassoulas/pySankey/tree/master. I'll be able to merge your pull request and release another version if you need.

**Comment by brianpenghe** [comment]
I installed it but when I called 
`from pySankeyBeta.sankey import sankey`
The module was not found. Any ideas?

**Comment by brianpenghe** [comment]
Nevermind it seems that it should be:
`from pysankey import sankey`

**Comment by brianpenghe** [comment]
> @kenosborne, PySankeyBeta is based on https://github.com/Pierre-Sassoulas/pySankey/tree/master. I'll be able to merge your pull request and release another version if you need.

I've installed the pySankeyBeta but the error is still there

**Comment by Pierre-Sassoulas** [comment]
It might still import the old one. Did you uninstall `PySankey` ? I'm not going to test this, but if I remember correctly, PySankeyBeta need, `from pysankey import sankey` while you probably had `from pysankey.sankey import sankey`. 

Do `pip3 uninstall PySankey` and you should have an understandable error.

**Comment by brianpenghe** [comment]
> pip3 uninstall PySankey

Yes I uninstalled PySankey. But when I reinstall pySankeyBeta again, it creates two folders under /usr/local/lib/python3.6/dist-packages/ : one for pySankeyBeta with no .py files in it, and one for pysankey with the older version. And when I do `from pysankey import sankey` it imports the version that the error's still there

**Comment by Pierre-Sassoulas** [comment]
`pySankeyBeta` should be in a non-empty directory called `pysankey` containing a sub-directory called `tests` (previously it was a `pySankey` directory with only `__init__.py` and `sankey.py` in it).

Can you also try `pip3 install -U pySankeyBeta` to make sure you have the latest version?
